In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
Books_df = pd.read_csv('Books.csv')
Users_df = pd.read_csv('Users.csv')
Ratings_df = pd.read_csv('Ratings.csv')

C:\Users\ABC\AppData\Local\Temp\ipykernel_9052\2328346950.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  Books_df = pd.read_csv('Books.csv')

In [3]:
print(Books_df.shape)
print(Users_df.shape)
print(Ratings_df.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

In [4]:
Books_df.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [5]:
Users_df.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [6]:
Ratings_df.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [7]:
Books_df.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [8]:
Users_df.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [9]:
Ratings_df.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

## 50 most popular books

In [10]:
Ratings_df.duplicated(subset = ['User-ID','ISBN']).sum()

0

In [11]:
Ratings_df.duplicated('ISBN').sum()

809224

In [12]:
Ratings_df.groupby(['ISBN'])['Book-Rating'].sum().head(20)

ISBN
 0330299891       6
 0375404120       3
 0586045007       0
 9022906116       7
 9032803328       0
 9044922564       0
 9044922572       0
 9044922718       0
 9044923161       0
 904492401X       0
 9061002273       0
#069580216X       0
#6612432          5
'9607092856'      0
'9607092910'     10
(THEWINDMILLP     0
)416195113        8
)440206529        0
)452273056        8
)553267833        7
Name: Book-Rating, dtype: int64

In [13]:
ratings_with_name = Ratings_df.merge(Books_df, on = 'ISBN')

In [14]:
num_rating_df = ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()

In [15]:
num_rating_df

                                               Book-Title  Book-Rating
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [16]:
num_rating_df.rename(columns={'Book-Rating':'Rating-Count'},inplace = True)

In [17]:
avg_rating_df = ratings_with_name.groupby('Book-Title').mean()['Book-Rating'].reset_index()
avg_rating_df.rename(columns={'Book-Rating':'Rating-Avg'},inplace = True)

In [18]:
avg_rating_df

                                               Book-Title  Rating-Avg
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [19]:
popularity_df  = num_rating_df.merge(avg_rating_df, on = 'Book-Title')

In [20]:
popularity_df.merge(Books_df, on = 'Book-Title').drop_duplicates('Book-Title')

,Book-Title,Rating-Count,Rating-Avg,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000,0590567330,Karen Hesse,1999,Hyperion Books for Children,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...,http://images.amazon.com/images/P/0590567330.0...
1,Always Have Popsicles,1,0.000000,0964147726,Rebecca Harvin,1994,Rebecca L. Harvin,http://images.amazon.com/images/P/0964147726.0...,http://images.amazon.com/images/P/0964147726.0...,http://images.amazon.com/images/P/0964147726.0...
2,Apple Magic (The Collector's series),1,0.000000,0942320093,Martina Boudreau,1984,Amer Cooking Guild,http://images.amazon.com/images/P/0942320093.0...,http://images.amazon.com/images/P/0942320093.0...,http://images.amazon.com/images/P/0942320093.0...
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000,0310232546,Nancy N. Rue,2001,Zonderkidz,http://images.amazon.com/images/P/0310232546.0...,http://images.amazon.com/images/P/0310232546.0...,http://images.amazon.com/images/P/0310232546.0...
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000,0962295701,Lou Mobley,1989,"Teleonet, Incorporated",http://images.amazon.com/images/P/0962295701.0...,http://images.amazon.com/images/P/0962295701.0...,http://images.amazon.com/images/P/0962295701.0...
...,...,...,...,...,...,...,...,...,...,...
270291,Ã?Â?lpiraten.,2,0.000000,3499232499,Janwillem van de Wetering,2002,Rowohlt Tb.,http://images.amazon.com/images/P/3499232499.0...,http://images.amazon.com/images/P/3499232499.0...,http://images.amazon.com/images/P/3499232499.0...
270292,Ã?Â?rger mit Produkt X. Roman.,4,5.250000,325721538X,Joan Aiken,1987,Diogenes Verlag,http://images.amazon.com/images/P/325721538X.0...,http://images.amazon.com/images/P/325721538X.0...,http://images.amazon.com/images/P/325721538X.0...
270293,Ã?Â?sterlich leben.,1,7.000000,3451274973,Anselm GrÃ?Â¼n,2001,"Herder, Freiburg",http://images.amazon.com/images/P/3451274973.0...,http://images.amazon.com/images/P/3451274973.0...,http://images.amazon.com/images/P/3451274973.0...
270294,Ã?Â?stlich der Berge.,3,2.666667,3442725739,David Guterson,2000,btb,http://images.amazon.com/images/P/3442725739.0...,http://images.amazon.com/images/P/3442725739.0...,http://images.amazon.com/images/P/3442725739.0...
270295,Ã?Â?thique en toc,2,4.000000,2842192508,Didier Daeninckx,1998,Baleine,http://images.amazon.com/images/P/2842192508.0...,http://images.amazon.com/images/P/2842192508.0...,http://images.amazon.com/images/P/2842192508.0...

In [21]:
popularity_df = popularity_df[popularity_df['Rating-Count']>=250].sort_values('Rating-Avg', ascending = False).head(50)

In [22]:
popular_df = popularity_df.merge(Books_df, on = 'Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','Rating-Count','Rating-Avg']]

In [23]:
popular_df.reset_index()

,index,Book-Title,Book-Author,Image-URL-M,Rating-Count,Rating-Avg
0,0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
1,3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
2,5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
3,9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
4,13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
5,16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
6,17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
7,26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
8,28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,260,4.880769
9,39,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
10,47,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
11,53,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,430,4.551163
12,55,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,449,4.545657
13,62,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
14,63,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,284,4.454225
15,72,Prodigal Summer: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...,253,4.450593
16,73,Neverwhere,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...,265,4.449057
17,78,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
18,84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,283,4.356890
19,85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
20,88,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,723,4.334716
21,89,The Hitchhiker's Guide to the Galaxy,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...,268,4.328358
22,98,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,335,4.289552
23,100,Into the Wild,Jon Krakauer,http://images.amazon.com/images/P/0385486804.0...,252,4.273810
24,103,Fahrenheit 451,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...,409,4.264059
25,116,Girl with a Pearl Earring,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...,526,4.218631
26,117,Outlander,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...,283,4.173145
27,123,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,http://images.amazon.com/images/P/0446672211.0...,585,4.105983
28,124,Seabiscuit: An American Legend,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...,275,4.098182
29,126,Life of Pi,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,664,4.088855
30,130,The Bean Trees,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,389,4.087404
31,133,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,http://images.amazon.com/images/P/1558743669.0...,265,4.086792
32,135,ANGELA'S ASHES,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...,279,4.075269
33,137,Good in Bed,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...,490,4.055102
34,139,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...,321,4.037383
35,140,American Gods,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...,302,4.006623
36,141,Skipping Christmas,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...,322,4.006211
37,147,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...,318,4.003145
38,149,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...,336,4.000000
39,157,The Color Purple,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,314,3.964968
40,163,Silence of the Lambs,Thomas Harris,http://images.amazon.com/images/P/0312924585.0...,256,3.960938
41,166,About a Boy,Nick Hornby,http://images.amazon.com/images/P/1573227331.0...,262,3.900763
42,173,Seven Up (A Stephanie Plum Novel),Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...,278,3.888489
43,175,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,http://images.amazon.com/images/P/0062502174.0...,266,3.875940
44,177,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...,269,3.825279
45,182,Suzanne's Diary for Nicholas,James Patterson,http://images.amazon.com/images/P/0316969443.0...,457,3.820569
46,186,Lord of the Flies,William Gerald Golding,http://images.amazon.com/images/P/0399501487.0...,259,3.818533
47,192,A Prayer for Owen Meany,John Irving,http://images.amazon.com/images/P/0345361792.0...,413,3.796610
48,194,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,http://images.amazon.com/images/P/0345313860.0...,301,3.777409
49,195,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,http://images.amazon.com/images/P/0316284955.0...,356,3.772472

In [24]:
popular_df['Image-URL-M'][0]

'http://images.amazon.com/images/P/0439136350.01.MZZZZZZZ.jpg'

## collaborating filtering

In [25]:
ratings_with_name.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...

In [26]:
# filter users who have rated min of 200 boook
x = ratings_with_name.groupby(['User-ID'])['Book-Rating'].count() >= 200
rating_over_200 = x[x].index

In [27]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(rating_over_200)]

In [28]:
# filter books which have more than 50 ratings
y = filtered_rating.groupby(['Book-Title'])['Book-Rating'].count()>=50

In [29]:
books_over_50 = y[y].index
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(books_over_50)]

In [30]:
# contains users who have rated more than 200 books and books which have more than 50 ratings
final_ratings

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [31]:
pt = final_ratings.pivot_table(index = 'Book-Title', columns = 'User-ID', values = 'Book-Rating')

In [32]:
pt.fillna(0,inplace = True)

In [33]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [34]:
from sklearn.metrics.pairwise import cosine_similarity

In [35]:
similarity_score = cosine_similarity(pt)

In [36]:
similarity_score[0]

array([1.        , 0.0999137 , 0.01189468, 0.        , 0.05229234,
       0.02703559, 0.08005247, 0.133798  , 0.03177829, 0.03573298,
       0.0226271 , 0.06592522, 0.020304  , 0.09425025, 0.1304464 ,
       0.08089641, 0.10866788, 0.0496928 , 0.02453052, 0.11405415,
       0.        , 0.13965274, 0.07645776, 0.05992325, 0.08499677,
       0.        , 0.06829594, 0.13307519, 0.07404925, 0.11854319,
       0.007483  , 0.01435345, 0.        , 0.07761015, 0.04406341,
       0.0151626 , 0.09251799, 0.01776199, 0.02543351, 0.07778745,
       0.11379679, 0.0554492 , 0.08139372, 0.08254087, 0.08560054,
       0.05350252, 0.0534403 , 0.26331669, 0.09527704, 0.05861375,
       0.08728505, 0.06575169, 0.        , 0.04353225, 0.01871487,
       0.        , 0.05484345, 0.00531237, 0.07674541, 0.05085288,
       0.18422052, 0.        , 0.01208759, 0.0290784 , 0.04169477,
       0.12354122, 0.16140808, 0.        , 0.1301383 , 0.06445396,
       0.        , 0.        , 0.        , 0.10686088, 0.02734449,
       0.04405541, 0.0254609 , 0.06699347, 0.01297391, 0.10248694,
       0.03167165, 0.01328403, 0.2306084 , 0.        , 0.10130612,
       0.06009182, 0.13811804, 0.11361279, 0.08116824, 0.00829019,
       0.0654278 , 0.        , 0.154433  , 0.03196179, 0.01041434,
       0.02513457, 0.02060486, 0.02618677, 0.02119881, 0.        ,
       0.01560485, 0.11802811, 0.04646003, 0.05669574, 0.06343332,
       0.        , 0.0464449 , 0.05137593, 0.02737765, 0.06356828,
       0.02061934, 0.02043932, 0.07231425, 0.01707714, 0.03274466,
       0.        , 0.01539053, 0.10755626, 0.16102364, 0.15115449,
       0.0607709 , 0.07930224, 0.05510014, 0.07266454, 0.03674914,
       0.05783708, 0.02879387, 0.03269331, 0.0461238 , 0.00980762,
       0.01628995, 0.07072309, 0.        , 0.        , 0.        ,
       0.02366065, 0.02988946, 0.09718526, 0.        , 0.01646698,
       0.02348879, 0.02738574, 0.        , 0.        , 0.01766268,
       0.02806762, 0.        , 0.05841023, 0.0207297 , 0.1007532 ,
       0.02695615, 0.10410091, 0.09644228, 0.13781517, 0.04878689,
       0.0850604 , 0.01374966, 0.        , 0.07634515, 0.0085956 ,
       0.04399795, 0.        , 0.01226526, 0.03900409, 0.07285412,
       0.01186594, 0.01838869, 0.02598903, 0.01396025, 0.1432484 ,
       0.05930779, 0.02512033, 0.02671383, 0.        , 0.14526273,
       0.05462639, 0.        , 0.03117647, 0.03550135, 0.        ,
       0.01912455, 0.21650925, 0.01476873, 0.0942457 , 0.02133718,
       0.01961781, 0.0526149 , 0.07075313, 0.01083057, 0.03556034,
       0.05840542, 0.        , 0.1431346 , 0.02032375, 0.10093291,
       0.09542563, 0.06440055, 0.1254017 , 0.08761537, 0.01117956,
       0.02396915, 0.        , 0.17585166, 0.05009695, 0.0464906 ,
       0.10570753, 0.12936761, 0.05763207, 0.05234846, 0.03389069,
       0.        , 0.08966431, 0.06224157, 0.04650607, 0.1484422 ,
       0.08204197, 0.12021004, 0.08558838, 0.07928432, 0.11864451,
       0.02371133, 0.00265847, 0.        , 0.        , 0.03577111,
       0.14888113, 0.03614062, 0.07266389, 0.09496112, 0.05276845,
       0.10003031, 0.07379678, 0.06261301, 0.0350914 , 0.01519651,
       0.01981277, 0.02400254, 0.        , 0.03263048, 0.02080469,
       0.01854434, 0.06631277, 0.01979871, 0.11481724, 0.07637937,
       0.08206016, 0.        , 0.01988328, 0.        , 0.04577455,
       0.08081263, 0.13615232, 0.01202785, 0.13163253, 0.07232632,
       0.11537437, 0.0480334 , 0.01579975, 0.02565328, 0.04692154,
       0.01909439, 0.09912675, 0.12916787, 0.        , 0.05368603,
       0.018133  , 0.        , 0.04388786, 0.03392925, 0.16078996,
       0.08248527, 0.06620646, 0.02910842, 0.        , 0.        ,
       0.0855621 , 0.0768255 , 0.04675675, 0.01430223, 0.02069234,
       0.04432946, 0.08450963, 0.0086322 , 0.02806576, 0.01970156,
       0.02352055, 0.12225698, 0.        , 0.02418693, 0.06352963,
       0.        , 0.05913776, 0.08410268, 0.13614834, 0.01927969,
       0.01228408, 0.08387275, 0.04319889, 0.02867419, 0.02184841,
       0.06373678, 0.07664613, 0.13914227, 0.1167132 , 0.0181063 ,
       0.13099699, 0.04685691, 0.09459803, 0.        , 0.20469829,
       0.07246533, 0.        , 0.12070545, 0.01015592, 0.02514496,
       0.        , 0.08721251, 0.03902569, 0.18515419, 0.02209215,
       0.0168586 , 0.02975525, 0.06644569, 0.09825353, 0.10198495,
       0.01640181, 0.12147727, 0.10002511, 0.034028  , 0.02598903,
       0.07456014, 0.0825619 , 0.01784878, 0.02121499, 0.14900173,
       0.        , 0.        , 0.01035915, 0.02097733, 0.0287069 ,
       0.        , 0.0202339 , 0.01164106, 0.00929156, 0.20143977,
       0.01514332, 0.03802323, 0.06509278, 0.087832  , 0.05762668,
       0.0604728 , 0.        , 0.01954386, 0.07641909, 0.15917803,
       0.06976966, 0.        , 0.14220017, 0.07367223, 0.02864158,
       0.04656746, 0.01760775, 0.11070589, 0.09539542, 0.07794022,
       0.08683203, 0.10660466, 0.        , 0.02061445, 0.0584957 ,
       0.0175095 , 0.05607437, 0.02056756, 0.09503665, 0.12770657,
       0.        , 0.06654309, 0.08898117, 0.        , 0.02709897,
       0.01465235, 0.0595601 , 0.01712107, 0.02407758, 0.01755262,
       0.11486693, 0.06301849, 0.13546717, 0.        , 0.06500118,
       0.        , 0.        , 0.05613944, 0.02207835, 0.00823155,
       0.02238413, 0.06952804, 0.14912013, 0.0588459 , 0.        ,
       0.08765604, 0.01506201, 0.09874723, 0.        , 0.01633246,
       0.        , 0.04892769, 0.15628767, 0.        , 0.13094201,
       0.12186923, 0.02269156, 0.01936178, 0.01077247, 0.02482524,
       0.00873007, 0.08034116, 0.01853973, 0.06844392, 0.02108042,
       0.12493306, 0.09741706, 0.08420688, 0.06191806, 0.02808902,
       0.04224353, 0.04585585, 0.05089432, 0.        , 0.08751806,
       0.00853122, 0.0966841 , 0.09965577, 0.        , 0.11991069,
       0.01713707, 0.01975982, 0.10072475, 0.1269322 , 0.08757792,
       0.08773485, 0.05194964, 0.07826898, 0.04479587, 0.05982032,
       0.02241559, 0.02245645, 0.06355335, 0.01866119, 0.        ,
       0.04425973, 0.        , 0.        , 0.0512667 , 0.01283226,
       0.        , 0.        , 0.04734378, 0.0715927 , 0.10088269,
       0.01674616, 0.09664898, 0.07883946, 0.00342853, 0.04634827,
       0.10836801, 0.05011243, 0.05520465, 0.        , 0.05931206,
       0.10522934, 0.        , 0.07360457, 0.        , 0.1329359 ,
       0.04673439, 0.15690035, 0.        , 0.01714618, 0.05298478,
       0.        , 0.07892531, 0.12754151, 0.00566885, 0.06966708,
       0.05288922, 0.05762264, 0.11811512, 0.05028948, 0.18790708,
       0.11199349, 0.06345598, 0.06237368, 0.        , 0.        ,
       0.10574617, 0.11107324, 0.04519976, 0.0177835 , 0.        ,
       0.01164473, 0.21422499, 0.05660341, 0.0423734 , 0.02578221,
       0.07089329, 0.05065985, 0.07055971, 0.10637858, 0.01584746,
       0.02369288, 0.0203974 , 0.13266966, 0.11435112, 0.08367406,
       0.08924327, 0.10561371, 0.06692383, 0.07990103, 0.13025344,
       0.        , 0.19459133, 0.02227429, 0.07855585, 0.        ,
       0.05608029, 0.06564822, 0.        , 0.19150929, 0.06144289,
       0.03409413, 0.09791433, 0.09349734, 0.02124117, 0.02257933,
       0.06309649, 0.06870929, 0.08067563, 0.1657143 , 0.07028453,
       0.01142064, 0.08321625, 0.17528356, 0.07801419, 0.01694899,
       0.16298684, 0.25717553, 0.17935621, 0.05456291, 0.04027312,
       0.06733334, 0.14085165, 0.22044678, 0.1871504 , 0.02331808,
       0.19510224, 0.01468892, 0.04900631, 0.12016584, 0.13836538,
       0.02408522, 0.08343632, 0.02302663, 0.12465093, 0.01055305,
       0.07163406, 0.0928744 , 0.03333919, 0.0700925 , 0.02238021,
       0.14949586, 0.08568461, 0.        , 0.        , 0.01830356,
       0.09521681, 0.04291124, 0.14820876, 0.01483113, 0.10042398,
       0.05568837, 0.0448179 , 0.05947579, 0.06403331, 0.14050562,
       0.08059795, 0.        , 0.04095625, 0.0221756 , 0.16934947,
       0.01860862, 0.15588905, 0.14304028, 0.        , 0.05787816,
       0.07526504, 0.07272845, 0.06378382, 0.06841054, 0.18434904,
       0.02430012, 0.01661191, 0.05297822, 0.04805997, 0.        ,
       0.11151141, 0.07795876, 0.12291611, 0.02247355, 0.05971528,
       0.02037015, 0.04433865, 0.10002638, 0.10450219, 0.02538357,
       0.00169243, 0.09619109, 0.0770845 , 0.02103713, 0.01572773,
       0.02031044, 0.09545575, 0.01780903, 0.18094225, 0.0520717 ,
       0.18438748, 0.05742651, 0.01449901, 0.11715626, 0.09587366,
       0.01021178, 0.10323797, 0.07421358, 0.07847313, 0.        ,
       0.22700367, 0.01046038, 0.1322457 , 0.04460839, 0.14068768,
       0.        , 0.12200992, 0.06289053, 0.02745084, 0.14074167,
       0.01676798, 0.09263709, 0.05045869, 0.17633624, 0.14735973,
       0.10708194, 0.12881891, 0.03853186, 0.03737679, 0.02400155,
       0.07643701, 0.03246169, 0.02930354, 0.02420211, 0.04115084,
       0.14073151, 0.12022969, 0.01471374, 0.02771242, 0.02077203,
       0.07201737, 0.08675349, 0.15485244, 0.06768953, 0.01033514,
       0.        , 0.09736247, 0.05564518, 0.0924443 , 0.00924546,
       0.13022242, 0.056451  , 0.        , 0.06548481, 0.02013856,
       0.        , 0.01792137, 0.        , 0.12329998, 0.07980979,
       0.08861857, 0.00711806, 0.07934504, 0.        , 0.04110338,
       0.0817707 , 0.0758563 , 0.        , 0.06967923, 0.02345695,
       0.01593088, 0.03638552, 0.05102579, 0.01110856, 0.00943819,
       0.12208488, 0.00886512, 0.05713332, 0.01724147, 0.11799012,
       0.07158663, 0.04205081])

In [53]:
def recommend (book_name):
    # fetch index
    index = np.where(pt.index==book_name)[0][0]
    similar_books = sorted(list(enumerate(similarity_score[index])),key = lambda x:x[1], reverse = True)[1:11]
    
    data = []
    for i in similar_books:
        item=[]
        temp_df = Books_df[Books_df['Book-Title'] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author'].values))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M'].values))
         
        data.append(item)
    return data

In [54]:
#similar book for specific book

similar_books = sorted(list(enumerate(similarity_score[0])),key = lambda x:x[1], reverse = True)[1:6]

In [55]:
recommend('1984')

[['Animal Farm',
  'George Orwell',
  'http://images.amazon.com/images/P/0451526341.01.MZZZZZZZ.jpg'],
 ["The Handmaid's Tale",
  'Margaret Atwood',
  'http://images.amazon.com/images/P/0449212602.01.MZZZZZZZ.jpg'],
 ['Brave New World',
  'Aldous Huxley',
  'http://images.amazon.com/images/P/0060809833.01.MZZZZZZZ.jpg'],
 ['The Vampire Lestat (Vampire Chronicles, Book II)',
  'ANNE RICE',
  'http://images.amazon.com/images/P/0345313860.01.MZZZZZZZ.jpg'],
 ['The Hours : A Novel',
  'Michael Cunningham',
  'http://images.amazon.com/images/P/0312243022.01.MZZZZZZZ.jpg'],
 ['Fahrenheit 451',
  'Ray Bradbury',
  'http://images.amazon.com/images/P/3257208626.01.MZZZZZZZ.jpg'],
 ['The Catcher in the Rye',
  'J.D. Salinger',
  'http://images.amazon.com/images/P/0316769487.01.MZZZZZZZ.jpg'],
 ['Lord of the Flies',
  'William Gerald Golding',
  'http://images.amazon.com/images/P/0399501487.01.MZZZZZZZ.jpg'],
 ['Naked',
  'David Sedaris',
  'http://images.amazon.com/images/P/0316777730.01.MZZZZZZZ.jpg'],
 ['The Hundred Secret Senses',
  'Amy Tan',
  'http://images.amazon.com/images/P/0399141146.01.MZZZZZZZ.jpg']]

In [58]:
import pickle

In [ ]:
pickle.dump(popular_df,open('popular.pkl','wb'))

In [60]:
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(Books_df,open('books_df.pkl','wb'))
pickle.dump(similarity_score,open('similarity_score.pkl','wb'))